// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/operator/lifecycle/dependent_lifecycle_manager.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/operator/lifecycle/dependent_lifecycle_manager.go --destination ./mocks/dependent_lifecycle_manager_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockDependentLifecycleManager is a mock of DependentLifecycleManager interface.
type MockDependentLifecycleManager struct {
	ctrl     *gomock.Controller
	recorder *MockDependentLifecycleManagerMockRecorder
}

// MockDependentLifecycleManagerMockRecorder is the mock recorder for MockDependentLifecycleManager.
type MockDependentLifecycleManagerMockRecorder struct {
	mock *MockDependentLifecycleManager
}

// NewMockDependentLifecycleManager creates a new mock instance.
func NewMockDependentLifecycleManager(ctrl *gomock.Controller) *MockDependentLifecycleManager {
	mock := &MockDependentLifecycleManager{ctrl: ctrl}
	mock.recorder = &MockDependentLifecycleManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependentLifecycleManager) EXPECT() *MockDependentLifecycleManagerMockRecorder {
	return m.recorder
}

// CleanupDependents mocks base method.
func (m *MockDependentLifecycleManager) CleanupDependents(currentDependents ...client.Object) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range currentDependents {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CleanupDependents", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupDependents indicates an expected call of CleanupDependents.
func (mr *MockDependentLifecycleManagerMockRecorder) CleanupDependents(currentDependents ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDependents", reflect.TypeOf((*MockDependentLifecycleManager)(nil).CleanupDependents), currentDependents...)
}

// UpdateDependentLifecycleInfo mocks base method.
func (m *MockDependentLifecycleManager) UpdateDependentLifecycleInfo(currentGenerationDependents []client.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDependentLifecycleInfo", currentGenerationDependents)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDependentLifecycleInfo indicates an expected call of UpdateDependentLifecycleInfo.
func (mr *MockDependentLifecycleManagerMockRecorder) UpdateDependentLifecycleInfo(currentGenerationDependents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDependentLifecycleInfo", reflect.TypeOf((*MockDependentLifecycleManager)(nil).UpdateDependentLifecycleInfo), currentGenerationDependents)
}
