// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/client/client.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/client/client.go --destination ./mocks/instana_agent_client_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	namespaces "github.com/instana/instana-agent-operator/pkg/k8s/object/builders/common/namespaces"
	result "github.com/instana/instana-agent-operator/pkg/result"
	gomock "go.uber.org/mock/gomock"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockInstanaAgentClient is a mock of InstanaAgentClient interface.
type MockInstanaAgentClient struct {
	ctrl     *gomock.Controller
	recorder *MockInstanaAgentClientMockRecorder
}

// MockInstanaAgentClientMockRecorder is the mock recorder for MockInstanaAgentClient.
type MockInstanaAgentClientMockRecorder struct {
	mock *MockInstanaAgentClient
}

// NewMockInstanaAgentClient creates a new mock instance.
func NewMockInstanaAgentClient(ctrl *gomock.Controller) *MockInstanaAgentClient {
	mock := &MockInstanaAgentClient{ctrl: ctrl}
	mock.recorder = &MockInstanaAgentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanaAgentClient) EXPECT() *MockInstanaAgentClientMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockInstanaAgentClient) Apply(ctx context.Context, obj client.Object, opts ...client.PatchOption) result.Result[client.Object] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Apply", varargs...)
	ret0, _ := ret[0].(result.Result[client.Object])
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockInstanaAgentClientMockRecorder) Apply(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockInstanaAgentClient)(nil).Apply), varargs...)
}

// Delete mocks base method.
func (m *MockInstanaAgentClient) Delete(ctx context.Context, obj client.Object, opts ...client.DeleteOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInstanaAgentClientMockRecorder) Delete(ctx, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInstanaAgentClient)(nil).Delete), varargs...)
}

// DeleteAllInTimeLimit mocks base method.
func (m *MockInstanaAgentClient) DeleteAllInTimeLimit(ctx context.Context, objects []client.Object, timeout, waitTime time.Duration, opts ...client.DeleteOption) result.Result[[]client.Object] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, objects, timeout, waitTime}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAllInTimeLimit", varargs...)
	ret0, _ := ret[0].(result.Result[[]client.Object])
	return ret0
}

// DeleteAllInTimeLimit indicates an expected call of DeleteAllInTimeLimit.
func (mr *MockInstanaAgentClientMockRecorder) DeleteAllInTimeLimit(ctx, objects, timeout, waitTime any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, objects, timeout, waitTime}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllInTimeLimit", reflect.TypeOf((*MockInstanaAgentClient)(nil).DeleteAllInTimeLimit), varargs...)
}

// Exists mocks base method.
func (m *MockInstanaAgentClient) Exists(ctx context.Context, gvk schema.GroupVersionKind, key client.ObjectKey) result.Result[bool] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, gvk, key)
	ret0, _ := ret[0].(result.Result[bool])
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MockInstanaAgentClientMockRecorder) Exists(ctx, gvk, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockInstanaAgentClient)(nil).Exists), ctx, gvk, key)
}

// Get mocks base method.
func (m *MockInstanaAgentClient) Get(ctx context.Context, key types.NamespacedName, obj client.Object, opts ...client.GetOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockInstanaAgentClientMockRecorder) Get(ctx, key, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInstanaAgentClient)(nil).Get), varargs...)
}

// GetAsResult mocks base method.
func (m *MockInstanaAgentClient) GetAsResult(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) result.Result[client.Object] {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAsResult", varargs...)
	ret0, _ := ret[0].(result.Result[client.Object])
	return ret0
}

// GetAsResult indicates an expected call of GetAsResult.
func (mr *MockInstanaAgentClientMockRecorder) GetAsResult(ctx, key, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsResult", reflect.TypeOf((*MockInstanaAgentClient)(nil).GetAsResult), varargs...)
}

// GetNamespacesWithLabels mocks base method.
func (m *MockInstanaAgentClient) GetNamespacesWithLabels(ctx context.Context) (namespaces.NamespacesDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespacesWithLabels", ctx)
	ret0, _ := ret[0].(namespaces.NamespacesDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespacesWithLabels indicates an expected call of GetNamespacesWithLabels.
func (mr *MockInstanaAgentClientMockRecorder) GetNamespacesWithLabels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespacesWithLabels", reflect.TypeOf((*MockInstanaAgentClient)(nil).GetNamespacesWithLabels), ctx)
}

// Patch mocks base method.
func (m *MockInstanaAgentClient) Patch(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.PatchOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, obj, patch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Patch indicates an expected call of Patch.
func (mr *MockInstanaAgentClientMockRecorder) Patch(ctx, obj, patch any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, obj, patch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockInstanaAgentClient)(nil).Patch), varargs...)
}

// Status mocks base method.
func (m *MockInstanaAgentClient) Status() client.SubResourceWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(client.SubResourceWriter)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockInstanaAgentClientMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockInstanaAgentClient)(nil).Status))
}
