// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/json_or_die/json.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/json_or_die/json.go --destination ./mocks/json_or_die_marshaler_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJsonOrDieMarshaler is a mock of JsonOrDieMarshaler interface.
type MockJsonOrDieMarshaler[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockJsonOrDieMarshalerMockRecorder[T]
}

// MockJsonOrDieMarshalerMockRecorder is the mock recorder for MockJsonOrDieMarshaler.
type MockJsonOrDieMarshalerMockRecorder[T any] struct {
	mock *MockJsonOrDieMarshaler[T]
}

// NewMockJsonOrDieMarshaler creates a new mock instance.
func NewMockJsonOrDieMarshaler[T any](ctrl *gomock.Controller) *MockJsonOrDieMarshaler[T] {
	mock := &MockJsonOrDieMarshaler[T]{ctrl: ctrl}
	mock.recorder = &MockJsonOrDieMarshalerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJsonOrDieMarshaler[T]) EXPECT() *MockJsonOrDieMarshalerMockRecorder[T] {
	return m.recorder
}

// MarshalOrDie mocks base method.
func (m *MockJsonOrDieMarshaler[T]) MarshalOrDie(obj T) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalOrDie", obj)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// MarshalOrDie indicates an expected call of MarshalOrDie.
func (mr *MockJsonOrDieMarshalerMockRecorder[T]) MarshalOrDie(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalOrDie", reflect.TypeOf((*MockJsonOrDieMarshaler[T])(nil).MarshalOrDie), obj)
}

// UnMarshalOrDie mocks base method.
func (m *MockJsonOrDieMarshaler[T]) UnMarshalOrDie(raw []byte) T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnMarshalOrDie", raw)
	ret0, _ := ret[0].(T)
	return ret0
}

// UnMarshalOrDie indicates an expected call of UnMarshalOrDie.
func (mr *MockJsonOrDieMarshalerMockRecorder[T]) UnMarshalOrDie(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnMarshalOrDie", reflect.TypeOf((*MockJsonOrDieMarshaler[T])(nil).UnMarshalOrDie), raw)
}
