// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/object/builders/common/env/remote_env_builder.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/object/builders/common/env/remote_env_builder.go --destination ./mocks/remote_env_builder_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	env "github.com/instana/instana-agent-operator/pkg/k8s/object/builders/common/env"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockEnvBuilderRemote is a mock of EnvBuilderRemote interface.
type MockEnvBuilderRemote struct {
	ctrl     *gomock.Controller
	recorder *MockEnvBuilderRemoteMockRecorder
}

// MockEnvBuilderRemoteMockRecorder is the mock recorder for MockEnvBuilderRemote.
type MockEnvBuilderRemoteMockRecorder struct {
	mock *MockEnvBuilderRemote
}

// NewMockEnvBuilderRemote creates a new mock instance.
func NewMockEnvBuilderRemote(ctrl *gomock.Controller) *MockEnvBuilderRemote {
	mock := &MockEnvBuilderRemote{ctrl: ctrl}
	mock.recorder = &MockEnvBuilderRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvBuilderRemote) EXPECT() *MockEnvBuilderRemoteMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockEnvBuilderRemote) Build(envVarsRemote ...env.EnvVarRemote) []v1.EnvVar {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range envVarsRemote {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Build", varargs...)
	ret0, _ := ret[0].([]v1.EnvVar)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockEnvBuilderRemoteMockRecorder) Build(envVarsRemote ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockEnvBuilderRemote)(nil).Build), envVarsRemote...)
}
