// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/operator/status/remote_agent_status_manager.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/operator/status/remote_agent_status_manager.go --destination ./mocks/remote_agent_status_manager_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1 "github.com/instana/instana-agent-operator/api/v1"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockInstanaAgentRemoteStatusManager is a mock of InstanaAgentRemoteStatusManager interface.
type MockInstanaAgentRemoteStatusManager struct {
	ctrl     *gomock.Controller
	recorder *MockInstanaAgentRemoteStatusManagerMockRecorder
}

// MockInstanaAgentRemoteStatusManagerMockRecorder is the mock recorder for MockInstanaAgentRemoteStatusManager.
type MockInstanaAgentRemoteStatusManagerMockRecorder struct {
	mock *MockInstanaAgentRemoteStatusManager
}

// NewMockInstanaAgentRemoteStatusManager creates a new mock instance.
func NewMockInstanaAgentRemoteStatusManager(ctrl *gomock.Controller) *MockInstanaAgentRemoteStatusManager {
	mock := &MockInstanaAgentRemoteStatusManager{ctrl: ctrl}
	mock.recorder = &MockInstanaAgentRemoteStatusManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanaAgentRemoteStatusManager) EXPECT() *MockInstanaAgentRemoteStatusManagerMockRecorder {
	return m.recorder
}

// AddAgentDeployment mocks base method.
func (m *MockInstanaAgentRemoteStatusManager) AddAgentDeployment(agentDeployment client.ObjectKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAgentDeployment", agentDeployment)
}

// AddAgentDeployment indicates an expected call of AddAgentDeployment.
func (mr *MockInstanaAgentRemoteStatusManagerMockRecorder) AddAgentDeployment(agentDeployment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAgentDeployment", reflect.TypeOf((*MockInstanaAgentRemoteStatusManager)(nil).AddAgentDeployment), agentDeployment)
}

// SetAgentOld mocks base method.
func (m *MockInstanaAgentRemoteStatusManager) SetAgentOld(agent *v1.InstanaAgentRemote) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAgentOld", agent)
}

// SetAgentOld indicates an expected call of SetAgentOld.
func (mr *MockInstanaAgentRemoteStatusManagerMockRecorder) SetAgentOld(agent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentOld", reflect.TypeOf((*MockInstanaAgentRemoteStatusManager)(nil).SetAgentOld), agent)
}

// SetAgentSecretConfig mocks base method.
func (m *MockInstanaAgentRemoteStatusManager) SetAgentSecretConfig(agentSecretConfig client.ObjectKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAgentSecretConfig", agentSecretConfig)
}

// SetAgentSecretConfig indicates an expected call of SetAgentSecretConfig.
func (mr *MockInstanaAgentRemoteStatusManagerMockRecorder) SetAgentSecretConfig(agentSecretConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAgentSecretConfig", reflect.TypeOf((*MockInstanaAgentRemoteStatusManager)(nil).SetAgentSecretConfig), agentSecretConfig)
}

// UpdateAgentStatus mocks base method.
func (m *MockInstanaAgentRemoteStatusManager) UpdateAgentStatus(ctx context.Context, reconcileErr error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentStatus", ctx, reconcileErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentStatus indicates an expected call of UpdateAgentStatus.
func (mr *MockInstanaAgentRemoteStatusManagerMockRecorder) UpdateAgentStatus(ctx, reconcileErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentStatus", reflect.TypeOf((*MockInstanaAgentRemoteStatusManager)(nil).UpdateAgentStatus), ctx, reconcileErr)
}
