// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/object/builders/common/volume/remote_volume_builder.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/object/builders/common/volume/remote_volume_builder.go --destination ./mocks/remote_volume_builder_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	volume "github.com/instana/instana-agent-operator/pkg/k8s/object/builders/common/volume"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockVolumeBuilderRemote is a mock of VolumeBuilderRemote interface.
type MockVolumeBuilderRemote struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeBuilderRemoteMockRecorder
}

// MockVolumeBuilderRemoteMockRecorder is the mock recorder for MockVolumeBuilderRemote.
type MockVolumeBuilderRemoteMockRecorder struct {
	mock *MockVolumeBuilderRemote
}

// NewMockVolumeBuilderRemote creates a new mock instance.
func NewMockVolumeBuilderRemote(ctrl *gomock.Controller) *MockVolumeBuilderRemote {
	mock := &MockVolumeBuilderRemote{ctrl: ctrl}
	mock.recorder = &MockVolumeBuilderRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeBuilderRemote) EXPECT() *MockVolumeBuilderRemoteMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockVolumeBuilderRemote) Build(volumes ...volume.RemoteVolume) ([]v1.Volume, []v1.VolumeMount) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range volumes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Build", varargs...)
	ret0, _ := ret[0].([]v1.Volume)
	ret1, _ := ret[1].([]v1.VolumeMount)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockVolumeBuilderRemoteMockRecorder) Build(volumes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockVolumeBuilderRemote)(nil).Build), volumes...)
}

// BuildFromUserConfig mocks base method.
func (m *MockVolumeBuilderRemote) BuildFromUserConfig() ([]v1.Volume, []v1.VolumeMount) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildFromUserConfig")
	ret0, _ := ret[0].([]v1.Volume)
	ret1, _ := ret[1].([]v1.VolumeMount)
	return ret0, ret1
}

// BuildFromUserConfig indicates an expected call of BuildFromUserConfig.
func (mr *MockVolumeBuilderRemoteMockRecorder) BuildFromUserConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildFromUserConfig", reflect.TypeOf((*MockVolumeBuilderRemote)(nil).BuildFromUserConfig))
}
