// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/object/builders/common/helpers/remote_helpers.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/object/builders/common/helpers/remote_helpers.go --destination ./mocks/remote_helpers_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockRemoteHelpers is a mock of RemoteHelpers interface.
type MockRemoteHelpers struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteHelpersMockRecorder
}

// MockRemoteHelpersMockRecorder is the mock recorder for MockRemoteHelpers.
type MockRemoteHelpersMockRecorder struct {
	mock *MockRemoteHelpers
}

// NewMockRemoteHelpers creates a new mock instance.
func NewMockRemoteHelpers(ctrl *gomock.Controller) *MockRemoteHelpers {
	mock := &MockRemoteHelpers{ctrl: ctrl}
	mock.recorder = &MockRemoteHelpersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteHelpers) EXPECT() *MockRemoteHelpersMockRecorder {
	return m.recorder
}

// ContainersSecretName mocks base method.
func (m *MockRemoteHelpers) ContainersSecretName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainersSecretName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ContainersSecretName indicates an expected call of ContainersSecretName.
func (mr *MockRemoteHelpersMockRecorder) ContainersSecretName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainersSecretName", reflect.TypeOf((*MockRemoteHelpers)(nil).ContainersSecretName))
}

// ImagePullSecrets mocks base method.
func (m *MockRemoteHelpers) ImagePullSecrets() []v1.LocalObjectReference {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePullSecrets")
	ret0, _ := ret[0].([]v1.LocalObjectReference)
	return ret0
}

// ImagePullSecrets indicates an expected call of ImagePullSecrets.
func (mr *MockRemoteHelpersMockRecorder) ImagePullSecrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePullSecrets", reflect.TypeOf((*MockRemoteHelpers)(nil).ImagePullSecrets))
}

// RemoteResourcesName mocks base method.
func (m *MockRemoteHelpers) RemoteResourcesName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteResourcesName")
	ret0, _ := ret[0].(string)
	return ret0
}

// RemoteResourcesName indicates an expected call of RemoteResourcesName.
func (mr *MockRemoteHelpersMockRecorder) RemoteResourcesName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteResourcesName", reflect.TypeOf((*MockRemoteHelpers)(nil).RemoteResourcesName))
}

// ServiceAccountName mocks base method.
func (m *MockRemoteHelpers) ServiceAccountName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceAccountName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ServiceAccountName indicates an expected call of ServiceAccountName.
func (mr *MockRemoteHelpersMockRecorder) ServiceAccountName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceAccountName", reflect.TypeOf((*MockRemoteHelpers)(nil).ServiceAccountName))
}

// SortEnvVarsByName mocks base method.
func (m *MockRemoteHelpers) SortEnvVarsByName(envVars []v1.EnvVar) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SortEnvVarsByName", envVars)
}

// SortEnvVarsByName indicates an expected call of SortEnvVarsByName.
func (mr *MockRemoteHelpersMockRecorder) SortEnvVarsByName(envVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortEnvVarsByName", reflect.TypeOf((*MockRemoteHelpers)(nil).SortEnvVarsByName), envVars)
}

// TLSIsEnabled mocks base method.
func (m *MockRemoteHelpers) TLSIsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TLSIsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TLSIsEnabled indicates an expected call of TLSIsEnabled.
func (mr *MockRemoteHelpersMockRecorder) TLSIsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TLSIsEnabled", reflect.TypeOf((*MockRemoteHelpers)(nil).TLSIsEnabled))
}

// TLSSecretName mocks base method.
func (m *MockRemoteHelpers) TLSSecretName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TLSSecretName")
	ret0, _ := ret[0].(string)
	return ret0
}

// TLSSecretName indicates an expected call of TLSSecretName.
func (mr *MockRemoteHelpersMockRecorder) TLSSecretName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TLSSecretName", reflect.TypeOf((*MockRemoteHelpers)(nil).TLSSecretName))
}

// UseContainersSecret mocks base method.
func (m *MockRemoteHelpers) UseContainersSecret() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseContainersSecret")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UseContainersSecret indicates an expected call of UseContainersSecret.
func (mr *MockRemoteHelpersMockRecorder) UseContainersSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseContainersSecret", reflect.TypeOf((*MockRemoteHelpers)(nil).UseContainersSecret))
}
