// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/operator/lifecycle/remote_dependent_lifecycle_manager.go
//
// Generated by this command:
//
//	mockgen --source ./pkg/k8s/operator/lifecycle/remote_dependent_lifecycle_manager.go --destination ./mocks/remote_dependent_lifecycle_manager_mock.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockRemoteDependentLifecycleManager is a mock of RemoteDependentLifecycleManager interface.
type MockRemoteDependentLifecycleManager struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteDependentLifecycleManagerMockRecorder
}

// MockRemoteDependentLifecycleManagerMockRecorder is the mock recorder for MockRemoteDependentLifecycleManager.
type MockRemoteDependentLifecycleManagerMockRecorder struct {
	mock *MockRemoteDependentLifecycleManager
}

// NewMockRemoteDependentLifecycleManager creates a new mock instance.
func NewMockRemoteDependentLifecycleManager(ctrl *gomock.Controller) *MockRemoteDependentLifecycleManager {
	mock := &MockRemoteDependentLifecycleManager{ctrl: ctrl}
	mock.recorder = &MockRemoteDependentLifecycleManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteDependentLifecycleManager) EXPECT() *MockRemoteDependentLifecycleManagerMockRecorder {
	return m.recorder
}

// CleanupDependents mocks base method.
func (m *MockRemoteDependentLifecycleManager) CleanupDependents(currentDependents ...client.Object) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range currentDependents {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CleanupDependents", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupDependents indicates an expected call of CleanupDependents.
func (mr *MockRemoteDependentLifecycleManagerMockRecorder) CleanupDependents(currentDependents ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupDependents", reflect.TypeOf((*MockRemoteDependentLifecycleManager)(nil).CleanupDependents), currentDependents...)
}

// UpdateDependentLifecycleInfo mocks base method.
func (m *MockRemoteDependentLifecycleManager) UpdateDependentLifecycleInfo(currentGenerationDependents []client.Object) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDependentLifecycleInfo", currentGenerationDependents)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDependentLifecycleInfo indicates an expected call of UpdateDependentLifecycleInfo.
func (mr *MockRemoteDependentLifecycleManagerMockRecorder) UpdateDependentLifecycleInfo(currentGenerationDependents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDependentLifecycleInfo", reflect.TypeOf((*MockRemoteDependentLifecycleManager)(nil).UpdateDependentLifecycleInfo), currentGenerationDependents)
}
